runtime: nodejs10

env_variables:
  PORT: 8080
  SECRET_KEY: 'secret'
  MONGO_URI: 'mongodb+srv://Mobility:Password1@mobility-dvxsj.mongodb.net/mobility?retryWrites=true&w=majority'
  UPLOAD_LOCATION: './upload'
  MAX_FILE_SIZE: '1000000'

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
